Manufacturer.create({username: 'shereen_0', password: 'password0', name: 'Shereen0',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_1', password: 'password1', name: 'Shereen1',email: 'Shereen@gmail.com', telephone:'44444444'})
Manufacturer.create({username: 'shereen_2', password: 'password2', name: 'Shereen2',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_3', password: 'password3', name: 'Shereen3',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_4', password: 'password4', name: 'Shereen4',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_5', password: 'password5', name: 'Shereen5',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_6', password: 'password6', name: 'Shereen6',email: 'Shereen@gmail.com', telephone:'44444444'})
Manufacturer.create({username: 'shereen_7', password: 'password7', name: 'Shereen7',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_8', password: 'password8', name: 'Shereen8',email: 'Shereen@gmail.com', telephone:'66666666'})
Manufacturer.create({username: 'shereen_9', password: 'password9', name: 'Shereen9',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_10', password: 'password10', name: 'Shereen10',email: 'Shereen@gmail.com', telephone:'66666666'})
Manufacturer.create({username: 'shereen_11', password: 'password11', name: 'Shereen11',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_12', password: 'password12', name: 'Shereen12',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_13', password: 'password13', name: 'Shereen13',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_14', password: 'password14', name: 'Shereen14',email: 'Shereen@gmail.com', telephone:'66666666'})
Manufacturer.create({username: 'shereen_15', password: 'password15', name: 'Shereen15',email: 'Shereen@gmail.com', telephone:'55555555'})
Manufacturer.create({username: 'shereen_16', password: 'password16', name: 'Shereen16',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_17', password: 'password17', name: 'Shereen17',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_18', password: 'password18', name: 'Shereen18',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_19', password: 'password19', name: 'Shereen19',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_20', password: 'password20', name: 'Shereen20',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_21', password: 'password21', name: 'Shereen21',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_22', password: 'password22', name: 'Shereen22',email: 'Shereen@gmail.com', telephone:'66666666'})
Manufacturer.create({username: 'shereen_23', password: 'password23', name: 'Shereen23',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_24', password: 'password24', name: 'Shereen24',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_25', password: 'password25', name: 'Shereen25',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_26', password: 'password26', name: 'Shereen26',email: 'Shereen@gmail.com', telephone:'44444444'})
Manufacturer.create({username: 'shereen_27', password: 'password27', name: 'Shereen27',email: 'Shereen@gmail.com', telephone:'44444444'})
Manufacturer.create({username: 'shereen_28', password: 'password28', name: 'Shereen28',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_29', password: 'password29', name: 'Shereen29',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_30', password: 'password30', name: 'Shereen30',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_31', password: 'password31', name: 'Shereen31',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_32', password: 'password32', name: 'Shereen32',email: 'Shereen@gmail.com', telephone:'66666666'})
Manufacturer.create({username: 'shereen_33', password: 'password33', name: 'Shereen33',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_34', password: 'password34', name: 'Shereen34',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_35', password: 'password35', name: 'Shereen35',email: 'Shereen@gmail.com', telephone:'66666666'})
Manufacturer.create({username: 'shereen_36', password: 'password36', name: 'Shereen36',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_37', password: 'password37', name: 'Shereen37',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_38', password: 'password38', name: 'Shereen38',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_39', password: 'password39', name: 'Shereen39',email: 'Shereen@gmail.com', telephone:'55555555'})
Manufacturer.create({username: 'shereen_40', password: 'password40', name: 'Shereen40',email: 'Shereen@gmail.com', telephone:'55555555'})
Manufacturer.create({username: 'shereen_41', password: 'password41', name: 'Shereen41',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_42', password: 'password42', name: 'Shereen42',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_43', password: 'password43', name: 'Shereen43',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_44', password: 'password44', name: 'Shereen44',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_45', password: 'password45', name: 'Shereen45',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_46', password: 'password46', name: 'Shereen46',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_47', password: 'password47', name: 'Shereen47',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_48', password: 'password48', name: 'Shereen48',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_49', password: 'password49', name: 'Shereen49',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_50', password: 'password50', name: 'Shereen50',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_51', password: 'password51', name: 'Shereen51',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_52', password: 'password52', name: 'Shereen52',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_53', password: 'password53', name: 'Shereen53',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_54', password: 'password54', name: 'Shereen54',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_55', password: 'password55', name: 'Shereen55',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_56', password: 'password56', name: 'Shereen56',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_57', password: 'password57', name: 'Shereen57',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_58', password: 'password58', name: 'Shereen58',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_59', password: 'password59', name: 'Shereen59',email: 'Shereen@gmail.com', telephone:'66666666'})
Manufacturer.create({username: 'shereen_60', password: 'password60', name: 'Shereen60',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_61', password: 'password61', name: 'Shereen61',email: 'Shereen@gmail.com', telephone:'44444444'})
Manufacturer.create({username: 'shereen_62', password: 'password62', name: 'Shereen62',email: 'Shereen@gmail.com', telephone:'66666666'})
Manufacturer.create({username: 'shereen_63', password: 'password63', name: 'Shereen63',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_64', password: 'password64', name: 'Shereen64',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_65', password: 'password65', name: 'Shereen65',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_66', password: 'password66', name: 'Shereen66',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_67', password: 'password67', name: 'Shereen67',email: 'Shereen@gmail.com', telephone:'55555555'})
Manufacturer.create({username: 'shereen_68', password: 'password68', name: 'Shereen68',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_69', password: 'password69', name: 'Shereen69',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_70', password: 'password70', name: 'Shereen70',email: 'Shereen@gmail.com', telephone:'55555555'})
Manufacturer.create({username: 'shereen_71', password: 'password71', name: 'Shereen71',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_72', password: 'password72', name: 'Shereen72',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_73', password: 'password73', name: 'Shereen73',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_74', password: 'password74', name: 'Shereen74',email: 'Shereen@gmail.com', telephone:'66666666'})
Manufacturer.create({username: 'shereen_75', password: 'password75', name: 'Shereen75',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_76', password: 'password76', name: 'Shereen76',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_77', password: 'password77', name: 'Shereen77',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_78', password: 'password78', name: 'Shereen78',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_79', password: 'password79', name: 'Shereen79',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_80', password: 'password80', name: 'Shereen80',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_81', password: 'password81', name: 'Shereen81',email: 'Shereen@gmail.com', telephone:'44444444'})
Manufacturer.create({username: 'shereen_82', password: 'password82', name: 'Shereen82',email: 'Shereen@gmail.com', telephone:'66666666'})
Manufacturer.create({username: 'shereen_83', password: 'password83', name: 'Shereen83',email: 'Shereen@gmail.com', telephone:'55555555'})
Manufacturer.create({username: 'shereen_84', password: 'password84', name: 'Shereen84',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_85', password: 'password85', name: 'Shereen85',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_86', password: 'password86', name: 'Shereen86',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_87', password: 'password87', name: 'Shereen87',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_88', password: 'password88', name: 'Shereen88',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_89', password: 'password89', name: 'Shereen89',email: 'Shereen@gmail.com', telephone:'88888888'})
Manufacturer.create({username: 'shereen_90', password: 'password90', name: 'Shereen90',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_91', password: 'password91', name: 'Shereen91',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_92', password: 'password92', name: 'Shereen92',email: 'Shereen@gmail.com', telephone:'55555555'})
Manufacturer.create({username: 'shereen_93', password: 'password93', name: 'Shereen93',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_94', password: 'password94', name: 'Shereen94',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_95', password: 'password95', name: 'Shereen95',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_96', password: 'password96', name: 'Shereen96',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_97', password: 'password97', name: 'Shereen97',email: 'Shereen@gmail.com', telephone:'44444444'})
Manufacturer.create({username: 'shereen_98', password: 'password98', name: 'Shereen98',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_99', password: 'password99', name: 'Shereen99',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_100', password: 'password100', name: 'Shereen100',email: 'Shereen@gmail.com', telephone:'77777777'})
Manufacturer.create({username: 'shereen_101', password: 'password101', name: 'Shereen101',email: 'Shereen@gmail.com', telephone:'44444444'})
Manufacturer.create({username: 'shereen_102', password: 'password102', name: 'Shereen102',email: 'Shereen@gmail.com', telephone:'22222222'})
Manufacturer.create({username: 'shereen_103', password: 'password103', name: 'Shereen103',email: 'Shereen@gmail.com', telephone:'44444444'})
Manufacturer.create({username: 'shereen_104', password: 'password104', name: 'Shereen104',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_105', password: 'password105', name: 'Shereen105',email: 'Shereen@gmail.com', telephone:'11111111'})
Manufacturer.create({username: 'shereen_106', password: 'password106', name: 'Shereen106',email: 'Shereen@gmail.com', telephone:'00000000'})
Manufacturer.create({username: 'shereen_107', password: 'password107', name: 'Shereen107',email: 'Shereen@gmail.com', telephone:'55555555'})
Manufacturer.create({username: 'shereen_108', password: 'password108', name: 'Shereen108',email: 'Shereen@gmail.com', telephone:'33333333'})
Manufacturer.create({username: 'shereen_109', password: 'password109', name: 'Shereen109',email: 'Shereen@gmail.com', telephone:'44444444'})


Shopper.create({username: 'shereen_0', password: 'password_0', name: 'Shereen0',email: 'Shereen@gmail.com', telephone:'11111111', address: '0 This is my address'})
Shopper.create({username: 'shereen_1', password: 'password_1', name: 'Shereen1',email: 'Shereen@gmail.com', telephone:'11111111', address: '1 This is my address'})
Shopper.create({username: 'shereen_2', password: 'password_2', name: 'Shereen2',email: 'Shereen@gmail.com', telephone:'00000000', address: '2 This is my address'})
Shopper.create({username: 'shereen_3', password: 'password_3', name: 'Shereen3',email: 'Shereen@gmail.com', telephone:'55555555', address: '3 This is my address'})
Shopper.create({username: 'shereen_4', password: 'password_4', name: 'Shereen4',email: 'Shereen@gmail.com', telephone:'33333333', address: '4 This is my address'})
Shopper.create({username: 'shereen_5', password: 'password_5', name: 'Shereen5',email: 'Shereen@gmail.com', telephone:'66666666', address: '5 This is my address'})
Shopper.create({username: 'shereen_6', password: 'password_6', name: 'Shereen6',email: 'Shereen@gmail.com', telephone:'88888888', address: '6 This is my address'})
Shopper.create({username: 'shereen_7', password: 'password_7', name: 'Shereen7',email: 'Shereen@gmail.com', telephone:'55555555', address: '7 This is my address'})
Shopper.create({username: 'shereen_8', password: 'password_8', name: 'Shereen8',email: 'Shereen@gmail.com', telephone:'66666666', address: '8 This is my address'})
Shopper.create({username: 'shereen_9', password: 'password_9', name: 'Shereen9',email: 'Shereen@gmail.com', telephone:'88888888', address: '9 This is my address'})
Shopper.create({username: 'shereen_10', password: 'password_10', name: 'Shereen10',email: 'Shereen@gmail.com', telephone:'77777777', address: '10 This is my address'})
Shopper.create({username: 'shereen_11', password: 'password_11', name: 'Shereen11',email: 'Shereen@gmail.com', telephone:'33333333', address: '11 This is my address'})
Shopper.create({username: 'shereen_12', password: 'password_12', name: 'Shereen12',email: 'Shereen@gmail.com', telephone:'55555555', address: '12 This is my address'})
Shopper.create({username: 'shereen_13', password: 'password_13', name: 'Shereen13',email: 'Shereen@gmail.com', telephone:'22222222', address: '13 This is my address'})
Shopper.create({username: 'shereen_14', password: 'password_14', name: 'Shereen14',email: 'Shereen@gmail.com', telephone:'55555555', address: '14 This is my address'})
Shopper.create({username: 'shereen_15', password: 'password_15', name: 'Shereen15',email: 'Shereen@gmail.com', telephone:'22222222', address: '15 This is my address'})
Shopper.create({username: 'shereen_16', password: 'password_16', name: 'Shereen16',email: 'Shereen@gmail.com', telephone:'66666666', address: '16 This is my address'})
Shopper.create({username: 'shereen_17', password: 'password_17', name: 'Shereen17',email: 'Shereen@gmail.com', telephone:'22222222', address: '17 This is my address'})
Shopper.create({username: 'shereen_18', password: 'password_18', name: 'Shereen18',email: 'Shereen@gmail.com', telephone:'11111111', address: '18 This is my address'})
Shopper.create({username: 'shereen_19', password: 'password_19', name: 'Shereen19',email: 'Shereen@gmail.com', telephone:'77777777', address: '19 This is my address'})
Shopper.create({username: 'shereen_20', password: 'password_20', name: 'Shereen20',email: 'Shereen@gmail.com', telephone:'55555555', address: '20 This is my address'})
Shopper.create({username: 'shereen_21', password: 'password_21', name: 'Shereen21',email: 'Shereen@gmail.com', telephone:'44444444', address: '21 This is my address'})
Shopper.create({username: 'shereen_22', password: 'password_22', name: 'Shereen22',email: 'Shereen@gmail.com', telephone:'33333333', address: '22 This is my address'})
Shopper.create({username: 'shereen_23', password: 'password_23', name: 'Shereen23',email: 'Shereen@gmail.com', telephone:'44444444', address: '23 This is my address'})
Shopper.create({username: 'shereen_24', password: 'password_24', name: 'Shereen24',email: 'Shereen@gmail.com', telephone:'22222222', address: '24 This is my address'})
Shopper.create({username: 'shereen_25', password: 'password_25', name: 'Shereen25',email: 'Shereen@gmail.com', telephone:'33333333', address: '25 This is my address'})
Shopper.create({username: 'shereen_26', password: 'password_26', name: 'Shereen26',email: 'Shereen@gmail.com', telephone:'77777777', address: '26 This is my address'})
Shopper.create({username: 'shereen_27', password: 'password_27', name: 'Shereen27',email: 'Shereen@gmail.com', telephone:'55555555', address: '27 This is my address'})
Shopper.create({username: 'shereen_28', password: 'password_28', name: 'Shereen28',email: 'Shereen@gmail.com', telephone:'66666666', address: '28 This is my address'})
Shopper.create({username: 'shereen_29', password: 'password_29', name: 'Shereen29',email: 'Shereen@gmail.com', telephone:'44444444', address: '29 This is my address'})
Shopper.create({username: 'shereen_30', password: 'password_30', name: 'Shereen30',email: 'Shereen@gmail.com', telephone:'11111111', address: '30 This is my address'})
Shopper.create({username: 'shereen_31', password: 'password_31', name: 'Shereen31',email: 'Shereen@gmail.com', telephone:'66666666', address: '31 This is my address'})
Shopper.create({username: 'shereen_32', password: 'password_32', name: 'Shereen32',email: 'Shereen@gmail.com', telephone:'00000000', address: '32 This is my address'})
Shopper.create({username: 'shereen_33', password: 'password_33', name: 'Shereen33',email: 'Shereen@gmail.com', telephone:'88888888', address: '33 This is my address'})
Shopper.create({username: 'shereen_34', password: 'password_34', name: 'Shereen34',email: 'Shereen@gmail.com', telephone:'88888888', address: '34 This is my address'})
Shopper.create({username: 'shereen_35', password: 'password_35', name: 'Shereen35',email: 'Shereen@gmail.com', telephone:'66666666', address: '35 This is my address'})
Shopper.create({username: 'shereen_36', password: 'password_36', name: 'Shereen36',email: 'Shereen@gmail.com', telephone:'22222222', address: '36 This is my address'})
Shopper.create({username: 'shereen_37', password: 'password_37', name: 'Shereen37',email: 'Shereen@gmail.com', telephone:'55555555', address: '37 This is my address'})
Shopper.create({username: 'shereen_38', password: 'password_38', name: 'Shereen38',email: 'Shereen@gmail.com', telephone:'77777777', address: '38 This is my address'})
Shopper.create({username: 'shereen_39', password: 'password_39', name: 'Shereen39',email: 'Shereen@gmail.com', telephone:'55555555', address: '39 This is my address'})
Shopper.create({username: 'shereen_40', password: 'password_40', name: 'Shereen40',email: 'Shereen@gmail.com', telephone:'77777777', address: '40 This is my address'})
Shopper.create({username: 'shereen_41', password: 'password_41', name: 'Shereen41',email: 'Shereen@gmail.com', telephone:'44444444', address: '41 This is my address'})
Shopper.create({username: 'shereen_42', password: 'password_42', name: 'Shereen42',email: 'Shereen@gmail.com', telephone:'22222222', address: '42 This is my address'})
Shopper.create({username: 'shereen_43', password: 'password_43', name: 'Shereen43',email: 'Shereen@gmail.com', telephone:'33333333', address: '43 This is my address'})
Shopper.create({username: 'shereen_44', password: 'password_44', name: 'Shereen44',email: 'Shereen@gmail.com', telephone:'22222222', address: '44 This is my address'})
Shopper.create({username: 'shereen_45', password: 'password_45', name: 'Shereen45',email: 'Shereen@gmail.com', telephone:'77777777', address: '45 This is my address'})
Shopper.create({username: 'shereen_46', password: 'password_46', name: 'Shereen46',email: 'Shereen@gmail.com', telephone:'77777777', address: '46 This is my address'})
Shopper.create({username: 'shereen_47', password: 'password_47', name: 'Shereen47',email: 'Shereen@gmail.com', telephone:'33333333', address: '47 This is my address'})
Shopper.create({username: 'shereen_48', password: 'password_48', name: 'Shereen48',email: 'Shereen@gmail.com', telephone:'66666666', address: '48 This is my address'})
Shopper.create({username: 'shereen_49', password: 'password_49', name: 'Shereen49',email: 'Shereen@gmail.com', telephone:'44444444', address: '49 This is my address'})
Shopper.create({username: 'shereen_50', password: 'password_50', name: 'Shereen50',email: 'Shereen@gmail.com', telephone:'77777777', address: '50 This is my address'})
Shopper.create({username: 'shereen_51', password: 'password_51', name: 'Shereen51',email: 'Shereen@gmail.com', telephone:'11111111', address: '51 This is my address'})
Shopper.create({username: 'shereen_52', password: 'password_52', name: 'Shereen52',email: 'Shereen@gmail.com', telephone:'11111111', address: '52 This is my address'})
Shopper.create({username: 'shereen_53', password: 'password_53', name: 'Shereen53',email: 'Shereen@gmail.com', telephone:'00000000', address: '53 This is my address'})
Shopper.create({username: 'shereen_54', password: 'password_54', name: 'Shereen54',email: 'Shereen@gmail.com', telephone:'88888888', address: '54 This is my address'})
Shopper.create({username: 'shereen_55', password: 'password_55', name: 'Shereen55',email: 'Shereen@gmail.com', telephone:'66666666', address: '55 This is my address'})
Shopper.create({username: 'shereen_56', password: 'password_56', name: 'Shereen56',email: 'Shereen@gmail.com', telephone:'88888888', address: '56 This is my address'})
Shopper.create({username: 'shereen_57', password: 'password_57', name: 'Shereen57',email: 'Shereen@gmail.com', telephone:'44444444', address: '57 This is my address'})
Shopper.create({username: 'shereen_58', password: 'password_58', name: 'Shereen58',email: 'Shereen@gmail.com', telephone:'00000000', address: '58 This is my address'})
Shopper.create({username: 'shereen_59', password: 'password_59', name: 'Shereen59',email: 'Shereen@gmail.com', telephone:'22222222', address: '59 This is my address'})
Shopper.create({username: 'shereen_60', password: 'password_60', name: 'Shereen60',email: 'Shereen@gmail.com', telephone:'44444444', address: '60 This is my address'})
Shopper.create({username: 'shereen_61', password: 'password_61', name: 'Shereen61',email: 'Shereen@gmail.com', telephone:'88888888', address: '61 This is my address'})
Shopper.create({username: 'shereen_62', password: 'password_62', name: 'Shereen62',email: 'Shereen@gmail.com', telephone:'11111111', address: '62 This is my address'})
Shopper.create({username: 'shereen_63', password: 'password_63', name: 'Shereen63',email: 'Shereen@gmail.com', telephone:'77777777', address: '63 This is my address'})
Shopper.create({username: 'shereen_64', password: 'password_64', name: 'Shereen64',email: 'Shereen@gmail.com', telephone:'55555555', address: '64 This is my address'})
Shopper.create({username: 'shereen_65', password: 'password_65', name: 'Shereen65',email: 'Shereen@gmail.com', telephone:'00000000', address: '65 This is my address'})
Shopper.create({username: 'shereen_66', password: 'password_66', name: 'Shereen66',email: 'Shereen@gmail.com', telephone:'44444444', address: '66 This is my address'})
Shopper.create({username: 'shereen_67', password: 'password_67', name: 'Shereen67',email: 'Shereen@gmail.com', telephone:'33333333', address: '67 This is my address'})
Shopper.create({username: 'shereen_68', password: 'password_68', name: 'Shereen68',email: 'Shereen@gmail.com', telephone:'66666666', address: '68 This is my address'})
Shopper.create({username: 'shereen_69', password: 'password_69', name: 'Shereen69',email: 'Shereen@gmail.com', telephone:'55555555', address: '69 This is my address'})
Shopper.create({username: 'shereen_70', password: 'password_70', name: 'Shereen70',email: 'Shereen@gmail.com', telephone:'77777777', address: '70 This is my address'})
Shopper.create({username: 'shereen_71', password: 'password_71', name: 'Shereen71',email: 'Shereen@gmail.com', telephone:'22222222', address: '71 This is my address'})
Shopper.create({username: 'shereen_72', password: 'password_72', name: 'Shereen72',email: 'Shereen@gmail.com', telephone:'88888888', address: '72 This is my address'})
Shopper.create({username: 'shereen_73', password: 'password_73', name: 'Shereen73',email: 'Shereen@gmail.com', telephone:'00000000', address: '73 This is my address'})
Shopper.create({username: 'shereen_74', password: 'password_74', name: 'Shereen74',email: 'Shereen@gmail.com', telephone:'77777777', address: '74 This is my address'})
Shopper.create({username: 'shereen_75', password: 'password_75', name: 'Shereen75',email: 'Shereen@gmail.com', telephone:'22222222', address: '75 This is my address'})
Shopper.create({username: 'shereen_76', password: 'password_76', name: 'Shereen76',email: 'Shereen@gmail.com', telephone:'77777777', address: '76 This is my address'})
Shopper.create({username: 'shereen_77', password: 'password_77', name: 'Shereen77',email: 'Shereen@gmail.com', telephone:'11111111', address: '77 This is my address'})
Shopper.create({username: 'shereen_78', password: 'password_78', name: 'Shereen78',email: 'Shereen@gmail.com', telephone:'22222222', address: '78 This is my address'})
Shopper.create({username: 'shereen_79', password: 'password_79', name: 'Shereen79',email: 'Shereen@gmail.com', telephone:'22222222', address: '79 This is my address'})
Shopper.create({username: 'shereen_80', password: 'password_80', name: 'Shereen80',email: 'Shereen@gmail.com', telephone:'22222222', address: '80 This is my address'})
Shopper.create({username: 'shereen_81', password: 'password_81', name: 'Shereen81',email: 'Shereen@gmail.com', telephone:'22222222', address: '81 This is my address'})
Shopper.create({username: 'shereen_82', password: 'password_82', name: 'Shereen82',email: 'Shereen@gmail.com', telephone:'44444444', address: '82 This is my address'})
Shopper.create({username: 'shereen_83', password: 'password_83', name: 'Shereen83',email: 'Shereen@gmail.com', telephone:'88888888', address: '83 This is my address'})
Shopper.create({username: 'shereen_84', password: 'password_84', name: 'Shereen84',email: 'Shereen@gmail.com', telephone:'00000000', address: '84 This is my address'})
Shopper.create({username: 'shereen_85', password: 'password_85', name: 'Shereen85',email: 'Shereen@gmail.com', telephone:'44444444', address: '85 This is my address'})
Shopper.create({username: 'shereen_86', password: 'password_86', name: 'Shereen86',email: 'Shereen@gmail.com', telephone:'33333333', address: '86 This is my address'})
Shopper.create({username: 'shereen_87', password: 'password_87', name: 'Shereen87',email: 'Shereen@gmail.com', telephone:'00000000', address: '87 This is my address'})
Shopper.create({username: 'shereen_88', password: 'password_88', name: 'Shereen88',email: 'Shereen@gmail.com', telephone:'00000000', address: '88 This is my address'})
Shopper.create({username: 'shereen_89', password: 'password_89', name: 'Shereen89',email: 'Shereen@gmail.com', telephone:'55555555', address: '89 This is my address'})
Shopper.create({username: 'shereen_90', password: 'password_90', name: 'Shereen90',email: 'Shereen@gmail.com', telephone:'00000000', address: '90 This is my address'})
Shopper.create({username: 'shereen_91', password: 'password_91', name: 'Shereen91',email: 'Shereen@gmail.com', telephone:'33333333', address: '91 This is my address'})
Shopper.create({username: 'shereen_92', password: 'password_92', name: 'Shereen92',email: 'Shereen@gmail.com', telephone:'66666666', address: '92 This is my address'})
Shopper.create({username: 'shereen_93', password: 'password_93', name: 'Shereen93',email: 'Shereen@gmail.com', telephone:'55555555', address: '93 This is my address'})
Shopper.create({username: 'shereen_94', password: 'password_94', name: 'Shereen94',email: 'Shereen@gmail.com', telephone:'33333333', address: '94 This is my address'})
Shopper.create({username: 'shereen_95', password: 'password_95', name: 'Shereen95',email: 'Shereen@gmail.com', telephone:'88888888', address: '95 This is my address'})
Shopper.create({username: 'shereen_96', password: 'password_96', name: 'Shereen96',email: 'Shereen@gmail.com', telephone:'88888888', address: '96 This is my address'})
Shopper.create({username: 'shereen_97', password: 'password_97', name: 'Shereen97',email: 'Shereen@gmail.com', telephone:'66666666', address: '97 This is my address'})
Shopper.create({username: 'shereen_98', password: 'password_98', name: 'Shereen98',email: 'Shereen@gmail.com', telephone:'88888888', address: '98 This is my address'})
Shopper.create({username: 'shereen_99', password: 'password_99', name: 'Shereen99',email: 'Shereen@gmail.com', telephone:'00000000', address: '99 This is my address'})
Shopper.create({username: 'shereen_100', password: 'password_100', name: 'Shereen100',email: 'Shereen@gmail.com', telephone:'11111111', address: '100 This is my address'})

Product.create({product_name: 'toy-0', manufacturer_id: 5,price: 0.0, number_in_stock: 0, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-1', manufacturer_id: 2,price: 1.0, number_in_stock: 1, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-2', manufacturer_id: 16,price: 2.0, number_in_stock: 2, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-3', manufacturer_id: 0,price: 3.0, number_in_stock: 3, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-4', manufacturer_id: 0,price: 4.0, number_in_stock: 4, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-5', manufacturer_id: 13,price: 5.0, number_in_stock: 5, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-6', manufacturer_id: 13,price: 6.0, number_in_stock: 6, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-7', manufacturer_id: 18,price: 7.0, number_in_stock: 7, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-8', manufacturer_id: 10,price: 8.0, number_in_stock: 8, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-9', manufacturer_id: 18,price: 9.0, number_in_stock: 9, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-10', manufacturer_id: 2,price: 10.0, number_in_stock: 10, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-11', manufacturer_id: 4,price: 11.0, number_in_stock: 11, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-12', manufacturer_id: 1,price: 12.0, number_in_stock: 12, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-13', manufacturer_id: 13,price: 13.0, number_in_stock: 13, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-14', manufacturer_id: 5,price: 14.0, number_in_stock: 14, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-15', manufacturer_id: 5,price: 15.0, number_in_stock: 15, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-16', manufacturer_id: 12,price: 16.0, number_in_stock: 16, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-17', manufacturer_id: 8,price: 17.0, number_in_stock: 17, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-18', manufacturer_id: 14,price: 18.0, number_in_stock: 18, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-19', manufacturer_id: 1,price: 19.0, number_in_stock: 19, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-20', manufacturer_id: 3,price: 20.0, number_in_stock: 20, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-21', manufacturer_id: 5,price: 21.0, number_in_stock: 21, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-22', manufacturer_id: 5,price: 22.0, number_in_stock: 22, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-23', manufacturer_id: 12,price: 23.0, number_in_stock: 23, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-24', manufacturer_id: 16,price: 24.0, number_in_stock: 24, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-25', manufacturer_id: 8,price: 25.0, number_in_stock: 25, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-26', manufacturer_id: 16,price: 26.0, number_in_stock: 26, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-27', manufacturer_id: 13,price: 27.0, number_in_stock: 27, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-28', manufacturer_id: 6,price: 28.0, number_in_stock: 28, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-29', manufacturer_id: 4,price: 29.0, number_in_stock: 29, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-30', manufacturer_id: 9,price: 30.0, number_in_stock: 30, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-31', manufacturer_id: 4,price: 31.0, number_in_stock: 31, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-32', manufacturer_id: 8,price: 32.0, number_in_stock: 32, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-33', manufacturer_id: 19,price: 33.0, number_in_stock: 33, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-34', manufacturer_id: 19,price: 34.0, number_in_stock: 34, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-35', manufacturer_id: 18,price: 35.0, number_in_stock: 35, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-36', manufacturer_id: 5,price: 36.0, number_in_stock: 36, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-37', manufacturer_id: 8,price: 37.0, number_in_stock: 37, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-38', manufacturer_id: 1,price: 38.0, number_in_stock: 38, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-39', manufacturer_id: 1,price: 39.0, number_in_stock: 39, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-40', manufacturer_id: 4,price: 40.0, number_in_stock: 40, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-41', manufacturer_id: 15,price: 41.0, number_in_stock: 41, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-42', manufacturer_id: 2,price: 42.0, number_in_stock: 42, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-43', manufacturer_id: 14,price: 43.0, number_in_stock: 43, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-44', manufacturer_id: 10,price: 44.0, number_in_stock: 44, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-45', manufacturer_id: 8,price: 45.0, number_in_stock: 45, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-46', manufacturer_id: 10,price: 46.0, number_in_stock: 46, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-47', manufacturer_id: 15,price: 47.0, number_in_stock: 47, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-48', manufacturer_id: 11,price: 48.0, number_in_stock: 48, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-49', manufacturer_id: 4,price: 49.0, number_in_stock: 49, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-50', manufacturer_id: 4,price: 50.0, number_in_stock: 50, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-51', manufacturer_id: 14,price: 51.0, number_in_stock: 51, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-52', manufacturer_id: 2,price: 52.0, number_in_stock: 52, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-53', manufacturer_id: 7,price: 53.0, number_in_stock: 53, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-54', manufacturer_id: 5,price: 54.0, number_in_stock: 54, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-55', manufacturer_id: 0,price: 55.0, number_in_stock: 55, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-56', manufacturer_id: 8,price: 56.0, number_in_stock: 56, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-57', manufacturer_id: 17,price: 57.0, number_in_stock: 57, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-58', manufacturer_id: 0,price: 58.0, number_in_stock: 58, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-59', manufacturer_id: 17,price: 59.0, number_in_stock: 59, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-60', manufacturer_id: 11,price: 60.0, number_in_stock: 60, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-61', manufacturer_id: 16,price: 61.0, number_in_stock: 61, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-62', manufacturer_id: 5,price: 62.0, number_in_stock: 62, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-63', manufacturer_id: 13,price: 63.0, number_in_stock: 63, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-64', manufacturer_id: 10,price: 64.0, number_in_stock: 64, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-65', manufacturer_id: 0,price: 65.0, number_in_stock: 65, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-66', manufacturer_id: 13,price: 66.0, number_in_stock: 66, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-67', manufacturer_id: 19,price: 67.0, number_in_stock: 67, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-68', manufacturer_id: 8,price: 68.0, number_in_stock: 68, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-69', manufacturer_id: 18,price: 69.0, number_in_stock: 69, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-70', manufacturer_id: 14,price: 70.0, number_in_stock: 70, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-71', manufacturer_id: 5,price: 71.0, number_in_stock: 71, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-72', manufacturer_id: 19,price: 72.0, number_in_stock: 72, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-73', manufacturer_id: 1,price: 73.0, number_in_stock: 73, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-74', manufacturer_id: 0,price: 74.0, number_in_stock: 74, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-75', manufacturer_id: 17,price: 75.0, number_in_stock: 75, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-76', manufacturer_id: 0,price: 76.0, number_in_stock: 76, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-77', manufacturer_id: 8,price: 77.0, number_in_stock: 77, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-78', manufacturer_id: 3,price: 78.0, number_in_stock: 78, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-79', manufacturer_id: 2,price: 79.0, number_in_stock: 79, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-80', manufacturer_id: 11,price: 80.0, number_in_stock: 80, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-81', manufacturer_id: 1,price: 81.0, number_in_stock: 81, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-82', manufacturer_id: 12,price: 82.0, number_in_stock: 82, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-83', manufacturer_id: 16,price: 83.0, number_in_stock: 83, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-84', manufacturer_id: 19,price: 84.0, number_in_stock: 84, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-85', manufacturer_id: 5,price: 85.0, number_in_stock: 85, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-86', manufacturer_id: 13,price: 86.0, number_in_stock: 86, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-87', manufacturer_id: 16,price: 87.0, number_in_stock: 87, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-88', manufacturer_id: 11,price: 88.0, number_in_stock: 88, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-89', manufacturer_id: 12,price: 89.0, number_in_stock: 89, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-90', manufacturer_id: 11,price: 90.0, number_in_stock: 90, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-91', manufacturer_id: 4,price: 91.0, number_in_stock: 91, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-92', manufacturer_id: 14,price: 92.0, number_in_stock: 92, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-93', manufacturer_id: 8,price: 93.0, number_in_stock: 93, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-94', manufacturer_id: 12,price: 94.0, number_in_stock: 94, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-95', manufacturer_id: 12,price: 95.0, number_in_stock: 95, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-96', manufacturer_id: 1,price: 96.0, number_in_stock: 96, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-97', manufacturer_id: 12,price: 97.0, number_in_stock: 97, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-98', manufacturer_id: 7,price: 98.0, number_in_stock: 98, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})
Product.create({product_name: 'toy-99', manufacturer_id: 12,price: 99.0, number_in_stock: 99, average_rating: 3.3, description: 'This is the description', product_information: 'This is the specs'})